latest:
	docker build --tag purjuscommunication/lbn-aws-php73-redis .
	docker push purjuscommunication/lbn-aws-php73-redis
	@echo "\n\e[91mtagger la nouvelle version \e[39m"
	@echo "docker tag {hash} purjuscommunication/lbn-aws-php73-redis:x.y.z"
	@echo "docker push purjuscommunication/lbn-aws-php73-redis:x.y.z"
