latest:
	docker build --tag purjuscommunication/lbn-aws-php72 .
	docker push purjuscommunication/lbn-aws-php72
	@echo "\n\e[91mtagger la nouvelle version \e[39m"
	@echo "docker tag {hash} purjuscommunication/lbn-aws-php72:x.y.z"
	@echo "docker push purjuscommunication/lbn-aws-php72:x.y.z"
